# Generated by Django 6.0.3 on 2026-03-06 09:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_owned', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SOLD', 'Sold'), ('RENTED', 'Rented')], default='PENDING', max_length=20)),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('is_for_rent', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cars', to=settings.AUTH_USER_MODEL)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='companyapp.dealershipcompany')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carsapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanical_status', models.TextField()),
                ('interior_status', models.TextField()),
                ('exterior_status', models.TextField()),
                ('condition_notes', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='carsapp.car')),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
